---
- name: debian | Installing etcd
  apt:
    name: etcd
    state: present
  become: true

- name: debian | Configuring etcd
  template:
    src: etc/default/etcd.j2
    dest: /etc/default/etcd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: restart etcd

